### ISSUE TITLE
MPI failures using mpipool.MPIPool

### ISSUE THREAD

**Issue by adrn** [bfarr/kombine#11]
I've been comparing emcee and kombine on a cluster using MPI to distribute the sampling and have been running into some issues with kombine that don't happen with emcee (_purely related to parallelization and not the algorithms themselves!_).

I'm using the master branch of [mpipool](https://github.com/adrn/mpipool) for MPI and running on Stampede (one of the NSF xsede machines). I'm using `loadbalance=True` because I'm using more walkers than compute cores (typically 512 walkers and 128 cores). With emcee, this works fine. With kombine, I get the following traceback:

```
Traceback (most recent call last):
  File "mcmc-troup.py", line 383, in <module>
    overwrite=args.overwrite)
  File "mcmc-troup.py", line 176, in main
    pool = get_pool(mpi=mpi, loadbalance=True)
  File "/work/03470/tg827691/anaconda/envs/ebak/lib/python3.5/site-packages/gala/util.py", line 59, in get_pool
    pool.wait()
  File "/work/03470/tg827691/projects/mpipool/mpipool/core.py", line 73, in wait
    task = self.comm.recv(source=0, tag=MPI.ANY_TAG, status=status)
  File "MPI/Comm.pyx", line 1192, in mpi4py.MPI.Comm.recv (src/mpi4py.MPI.c:106889)
  File "MPI/msgpickle.pxi", line 292, in mpi4py.MPI.PyMPI_recv (src/mpi4py.MPI.c:43053)
  File "MPI/msgpickle.pxi", line 143, in mpi4py.MPI.Pickle.load (src/mpi4py.MPI.c:41248)
_pickle.UnpicklingError
```

If I reduce the number of walkers (to ~200), the `UnpicklingError` goes away, which leads me to also suspect that it is somehow related to MPI buffer size or message size limits. I'll take a look at the kombine source again to see if there is any obvious issue, but I'm an MPI novice so any support would be appreciated!

This seems to be related to @dfm's [gist](https://gist.github.com/dfm/4176241) -- wondering if he ever found a solution? Also pinging @juliohm.

**Comment by adrn** [comment]
Some more information:
- The MPI implementation used on the cluster is MVAPICH2
- [Here is a minimal bit of code](https://gist.github.com/adrn/40d99d54236cf75ebf75701d2b0595d7#file-kombine-mpipool-py) that produces the error.
- Interestingly, using the MPI pool implementation from [this thread](https://groups.google.com/forum/#!topic/mpi4py/OJG5eZ2f-Pg) does not produce this error. See [this code](https://gist.github.com/adrn/40d99d54236cf75ebf75701d2b0595d7#file-kombine-custompool-py) for an example.

**Comment by adrn** [comment]
I just tested on a different cluster that uses openMPI v1.6.5 and I see the same behavior.

**Comment by juliohm** [comment]
@adrn , I don't remember what exactly I did, but you can see that I used this MPI pool class instead: https://github.com/juliohm/HUM/blob/master/pyhum/utils.py#L24

Good luck.

**Comment by bfarr** [comment]
I haven't been able to look into this too deeply yet, but I've managed to reproduce `UnpicklingError`s locally.

If I run without load balancing it seems to go away, and it looks like the MPI pool class pointed to by @juliohm doesn't do any load balancing either.

@adrn, do you get `UnpicklingError` with load balancing off?  If `emcee` works fine for you with the same configuration, it would be surprising if it were a problem with the load balancing...
