### ISSUE TITLE
Kombine version of pypi out of order

### ISSUE THREAD

**Issue by ahnitz** [bfarr/kombine#15]
On pypi there is still a 1.0 version that is *older* than those in the 0.8 series. Could this be deactivated or the current released version advance to beyond 1.0? For the time being it is not possible to depend on the *latest* version in a normal way (by specifying a minimum version).

**Comment by bfarr** [comment]
Thanks for pointing this out.  The older-newer versions have been removed.  Those must have been from when I was young and naive, getting everything set up on pypi for the first time.  Let me know if you still have issues.
