### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by eteq** [bfarr/kombine#5]
Having thrown kombine to the wolves by presenting it's impressive capabilities at the #LGAstat conference, it would be fantastic if kombine had some (sphinx?) documentation describing basic use, background, and API.  (Perhaps the [astropy affiliated package template](https://github.com/astropy/package-template) can be of use here?)

cc @bfarr @adrn

**Comment by bfarr** [comment]
You are very right.  I'll get on generating some documentation ASAP.  Thanks for pointing out the astropy templates.

**Comment by eteq** [comment]
Cool - feel free to ping me or Adrian, either on github or in-person (at least until the end of the conference)

**Comment by bfarr** [comment]
I've created some [barebones documentation](http://home.uchicago.edu/~farr/kombine/) for now, which should help people get up and running.  More detailed documentation, including 'advanced' features, is coming soon.

**Comment by eteq** [comment]
@bfarr - what about API docs?  That's more what I was thinking when linking the affiliated package template - the `automodapi` sphinx extension typically "just works" if you have docstrings that are valid ReST.  (Note that you can use that stuff independently of astropy or the affiliated package template by just using the `astropy_helpers` package, which is independent of `astropy` itself).

**Comment by bfarr** [comment]
Sorry, I lost the links in `index.rst` to the API docs somewhere along the way.  It should be there now.

Thanks for pointing that out!

**Comment by eteq** [comment]
Gotcha, cool!
